# Generated by Django 4.2 on 2024-10-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_time', models.DurationField()),
                ('break_time', models.DurationField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('completion_status', models.BooleanField(default=False)),
                ('daily_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.dailyprogram')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('daily_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.dailyprogram')),
                ('lesson1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson1_break', to='lessons.dailylesson')),
                ('lesson2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson2_break', to='lessons.dailylesson')),
            ],
        ),
    ]
